In [15]:
#load data
import pandas as pd
data=pd.read_csv("raw_students.csv")
data

      student_id       name           subject  score        date attendance
0           1086       Dale  Computer Science   64.0  2021-08-31        NaN
1           1320       John       Mathematics   78.0  2021-02-27    Present
2           1327      Scott  Computer Science   74.0  2022-09-05    Present
3           1327       Todd  Computer Science   60.0  2022-09-19    Present
4           1327      Bryce  Computer Science    NaN  2024-09-11    Present
...          ...        ...               ...    ...         ...        ...
1998        1339  Elizabeth           Physics   66.0         NaN     Absent
1999        1029    Stephen           Physics   71.0         NaN     Absent
2000        1200    Matthew           Biology   61.0  2020-01-19        NaN
2001        1007    Michael           Physics   95.0         NaN     Absent
2002        1369      Tonya  Computer Science   89.0  2020-10-30    Present

[2003 rows x 6 columns]

In [16]:
#show duplicates numbers
data.duplicated().sum()

np.int64(50)

In [17]:
#show duplicates in data
data[data.duplicated()]

      student_id       name           subject  score        date attendance
1953        1200        Amy           Physics   69.0  2022-04-28     Absent
1954        1153     Isaiah           Biology   79.0  2023-06-06     Absent
1955        1312      Aaron           Physics   79.0  2021-05-11    Present
1956        1414    Spencer       Mathematics   69.0  2023-11-21        NaN
1957        1331     Robert  Computer Science   80.0  2024-06-16     Absent
1958        1395       Jose       Mathematics   84.0  2024-01-13        NaN
1959        1146       Lori           Physics   69.0  2022-01-18        NaN
1960        1400     Donald           Physics    NaN  2023-11-16     Absent
1961        1387      Scott  Computer Science    NaN  2021-06-04     Absent
1962        1284      David  Computer Science   90.0  2023-02-24        NaN
1963        1472    Heather  Computer Science   87.0  2021-08-01        NaN
1964        1224     Angela       Mathematics   80.0  2021-04-11        NaN
1965        1151       Dean           Biology    NaN  2024-02-10    Present
1966        1420      Emily  Computer Science   89.0  2022-03-31     Absent
1967        1139    Antonio  Computer Science   61.0  2021-11-28        NaN
1968        1428      Steve  Computer Science   93.0  2023-04-02     Absent
1969        1216    Yesenia           Physics   92.0  2020-12-27    Present
1970        1414       John           Physics   96.0  2024-07-08    Present
1971        1165    Timothy           Physics   84.0         NaN     Absent
1972        1437      James           Physics    NaN         NaN    Present
1973        1469    Tiffany  Computer Science   65.0  2024-09-30    Present
1974        1444     Sharon           Biology   66.0  2024-01-06    Present
1975        1483       Jose           Biology   73.0  2024-12-10    Present
1976        1245       Kyle           Biology    NaN  2023-07-01    Present
1977        1297    Rebecca               NaN   88.0  2020-12-07        NaN
1978        1125    Beverly       Mathematics   97.0         NaN    Present
1979        1088     Steven  Computer Science   93.0  2022-04-15     Absent
1980        1055       Cory  Computer Science   71.0  2023-05-18     Absent
1981        1241     Thomas               NaN   87.0         NaN     Absent
1982        1031    Melissa           Biology   71.0  2020-10-05    Present
1983        1219     Thomas  Computer Science   66.0         NaN    Present
1984        1203   Jennifer       Mathematics   69.0  2023-03-26     Absent
1985        1444      Kayla           Biology   92.0  2024-02-20     Absent
1986        1229      Jason               NaN   68.0  2024-08-18        NaN
1987        1142      David           Physics   76.0  2022-09-14     Absent
1988        1219    Heather           Physics   79.0  2024-10-15     Absent
1989        1313      James       Mathematics   64.0         NaN    Present
1990        1232    Antonio  Computer Science   69.0  2024-09-06        NaN
1991        1021     Alyssa  Computer Science   99.0  2020-02-12    Present
1992        1037    Stephen  Computer Science   70.0  2021-04-13     Absent
1993        1244       Mark           Biology   96.0  2020-05-19        NaN
1994        1448     Olivia           Physics   71.0  2022-11-15    Present
1995        1371      David       Mathematics   80.0  2024-01-16    Present
1996        1125    Crystal       Mathematics   90.0  2023-10-31    Present
1997        1056    Michael           Biology   60.0  2020-06-25     Absent
1998        1339  Elizabeth           Physics   66.0         NaN     Absent
1999        1029    Stephen           Physics   71.0         NaN     Absent
2000        1200    Matthew           Biology   61.0  2020-01-19        NaN
2001        1007    Michael           Physics   95.0         NaN     Absent
2002        1369      Tonya  Computer Science   89.0  2020-10-30    Present

In [18]:
#remove duplicates
data.drop_duplicates(inplace=True)

In [19]:
#check about duplicates
data.duplicated().sum()

np.int64(0)

In [31]:
#convert dates from object to date
data['date']=pd.to_datetime(data['date'])

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1953 entries, 0 to 1952
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  1953 non-null   int64
 1   name        1930 non-null   object
 2   subject     1855 non-null   object
 3   score       1637 non-null   float64
 4   date        1698 non-null   datetime64[ns]
 5   attendance  1579 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 106.8+ KB

In [23]:
#show number of nulls
data.isnull().sum()

student_id      0
name           23
subject        98
score         316
date          255
attendance    374
dtype: int64

In [44]:
#fix nulls 
subject_means = data.groupby('subject')['score'].transform('mean')
data['score'] = data['score'].fillna(subject_means)

data['score'] = data['score'].fillna(data['score'].mean())

data['attendance'] = data['attendance'].fillna('Unknown')

data['subject'] = data['subject'].fillna('Unknown')

data['name'] = data['name'].fillna('Unknown')

data['date']=pd.to_datetime(data['date'],errors='coerce')
data['date']=data['date'].fillna(pd.to_datetime('today'))

In [45]:
#check about nulls
data.isnull().sum()

student_id    0
name          0
subject       0
score         0
date          0
attendance    0
dtype: int64

In [46]:
#categorize performance 
def categorize_performance(score):
    if score >=85:
        return "High"
    elif score >=60:
        return "Medium"
    else:
        return "Low"

In [47]:
#add now column(categorize performance )
data['categorize_performance']=data['score'].apply(categorize_performance)

In [48]:
data.head()

,student_id,name,subject,score,date,attendance,categorize_performance
0,1086,Dale,Computer Science,64.000000,2021-08-31,Unknown,Medium
1,1320,John,Mathematics,78.000000,2021-02-27,Present,Medium
2,1327,Scott,Computer Science,74.000000,2022-09-05,Present,Medium
3,1327,Todd,Computer Science,60.000000,2022-09-19,Present,Medium
4,1327,Bryce,Computer Science,78.356139,2024-09-11,Present,Medium

In [49]:
data.to_csv('cleaned_students.csv',index=False)